CREATE TABLE Dictionaries
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Value] NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Categories
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Value] NVARCHAR(100) NOT NULL
);

CREATE TABLE Authors
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[First] NVARCHAR(100) NOT NULL,
[Last] NVARCHAR(100) NOT NULL
);

CREATE TABLE ShippingDetails 
(
[Id] INT IDENTITY (1, 1) PRIMARY KEY,
[FirstName] NVARCHAR (MAX) NOT NULL,
[LastName] NVARCHAR (MAX) NOT NULL,
[Line1] NVARCHAR (MAX) NOT NULL,
[Line2] NVARCHAR (MAX) NULL,
[Line3] NVARCHAR (MAX) NULL,
[City]  NVARCHAR (MAX) NOT NULL,
[Zip]   NVARCHAR (MAX) NOT NULL,
[Country] NVARCHAR (MAX) NOT NULL
);

CREATE TABLE Books
(
[Id] INT IDENTITY(1,1) PRIMARY KEY,
[Title] NVARCHAR(100) NOT NULL,
[Description] NVARCHAR(500),
[CategoryId] INT FOREIGN KEY REFERENCES Categories(Id), 
[AuthorId] INT FOREIGN KEY REFERENCES Authors(Id), 
[Price] DECIMAL(16, 2) NOT NULL
);

CREATE TABLE Orders 
(
[Id] INT IDENTITY (1, 1) PRIMARY KEY,
[OrderDate] DATETIME2(0),
[ShippingDetailId] INT FOREIGN KEY REFERENCES ShippingDetails(Id)
);

CREATE TABLE OrderDetails 
(
[Id] INT IDENTITY (1, 1) PRIMARY KEY,
[OrderId] INT FOREIGN KEY REFERENCES Orders(Id),
[BookId] INT FOREIGN KEY REFERENCES Books(Id),
[Amount] INT
);

INSERT INTO Authors(First, Last) values ('Nicholas', 'Sparks');
...
COMMIT;